// React/Practice/first-react-app/src/Components/App.js
import React, { Component } from 'react';
import './App.css';
import Title from './Title/Title'

class App extends Component {
  render() {
    return (
      <div className="App">
        <div className="container py-5">
          <div className="row">
            <div className="col-sm-8 offset-sm-2">
              <Title></Title>
            </div>
          </div>
        </div>
      </div>
    );
  }
}

export default App;

// Vue/Practice/06-Routing/src/App.vue
<template>
    <div class="container">
        <div class="row">
            <div class="col-xs-12 col-sm-8 col-sm-offset-2 col-md-6 col-md-offset-3">
                <app-header></app-header>
                <hr>
                <router-view></router-view>
            </div>
        </div>
    </div>
</template>

<script>
    import Header from './components/Header.vue'
    export default {
        components: {
            appHeader: Header
        }
    }
</script>

<style>
</style>
