// React/Practice/first-react-app/src/Components/App.js
import React, { Component } from 'react';
import './App.css';
import Title from './Title/Title'

class App extends Component {
  render() {
    return (
      <div className="App">
        <div className="container py-5">
          <div className="row">
            <div className="col-sm-8 offset-sm-2">
              <Title></Title>
            </div>
          </div>
        </div>
      </div>
    );
  }
}

export default App;

// Vue/Practice/07-Vuex/src/App.vue
<template>
    <div class="container">
        <div class="row">
            <div class="col-xs-12 col-sm-8 col-sm-offset-2 col-md-6 col-md-offset-3">
                <h1>Vuex</h1>
                <app-result></app-result>
                <app-another-result></app-another-result>
                <hr>
                <app-counter></app-counter>
            </div>
        </div>
    </div>
</template>

<script>
    import Counter from './components/Counter.vue';
    import Result from './components/Result.vue';
    import NewResult from './components/AnotherResult.vue'

    export default {
        components: {
            appCounter: Counter,
            appResult: Result,
            appAnotherResult: NewResult
        }
    }
</script>
